### ISSUE TITLE
How can I use this tool?

### ISSUE THREAD

**Issue by kacnje** [theJayTea/WritingTools#11] opened 2024-10-21 07:31 UTC
I ran the program as an administrator. I wrote two paragraphs of text in English, selected all, and pressed the shortcut key. The text was deleted, and a small dialog appeared. But what can I do now?

![image](https://github.com/user-attachments/assets/19d6a75d-6536-4b89-94da-b74c71edf6e9)

**Comment by theJayTea** [comment] 2024-10-21 07:34
Hey! This is the same as issue #3 , except that with the new update it shows this box when no text is selected.

To fix it right now, change your shortcut key to **ctrl+`** (the key under escape) or **ctrl+j** and restart Writing Tools.

**Comment by kacnje** [comment] 2024-10-21 07:40
Agree. 
But I can't change the shortcut key (as described in issue #3 - and probably is better to talk there).

**Comment by theJayTea** [comment] 2024-10-21 07:54
Closing as duplicate of #3

**Closed by theJayTea** 2024-10-21 07:54 UTC
