### ISSUE TITLE
Method of defining presets and templates like those already available in the UX

### ISSUE THREAD

**Issue by apoapostolov** [theJayTea/WritingTools#13] opened 2024-10-21 14:23 UTC
This can be done with a JSON format of defining additional prompts that will extend the list of 8 options in the UX with new prompts. This allows some power users to define prompts that take the selected text and do complex and specialized transformations that are outside the scope of the basic ones.

In fact, making even the default prompts to be not hardcoded but part of a default JSON format that power users can learn from and extend with their new prompts, or remove those that are not useful to them to open space for their own takes, or rewrite the standard default prompts to other customized versions, is an even better approach.

**Comment by theJayTea** [comment] 2024-10-21 16:40
This is something I'll add in a future update :)

I'll let you modify what each of the buttons are called and their respective system prompts with a prompts.json file.

You can already modify the buttons' icons haha.

**Comment by theJayTea** [comment] 2024-11-10 17:17
Duplicate of #38

**Closed by theJayTea** 2024-11-10 17:17 UTC
Labels: suggestion
